autoshop/autoshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('shop.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

autoshop/shop/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView
from django.contrib import admin
from . import views

urlpatterns = [
    path('category/<str:category_slug>/', views.category_view, name='category_detail'),
    path('product/<str:product_slug>/', views.product_view, name='product_detail'),
    path('cart/', views.cart_view, name='cart'),
    path('add_to_cart/', views.add_to_cart_view, name='add_to_cart'),
    path('remove_from_cart/', views.remove_from_cart_view, name='remove_from_cart'),
    path('change_item_qty/', views.change_item_qty, name='change_item_qty'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('order/', views.order_create_view, name='create_order'),
    path('make_order/', views.make_order_view, name='make_order'),
    path('thank_you/', TemplateView.as_view(template_name='thank_you.html'), name='thank_you'),
    path('account/', views.account_view, name='account'),
    path('registration/', views.registration_view, name='registration'),
    path('login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('base')), name='logout'),
    path('', views.base_view, name='base'),
    # path('search-form/', views.search_form),
    path('search/', views.search, name='search'),
]

autoshop/shop/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.urls import reverse
from transliterate import translit
from decimal import Decimal
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_slug':self.slug})


def pre_save_category_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(translit(str(instance.name), reversed = True))
        instance.slug = slug

pre_save.connect(pre_save_category_slug, sender=Category)


class Brand(models.Model):

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)


class ProductManager(models.Manager):
    def all(self, *args, **kwargs):
        return super(ProductManager, self).get_queryset().filter(available=True)

class Product(models.Model):

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to=image_folder)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    available = models.BooleanField(default=True)
    objects = ProductManager()

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_slug':self.slug})

class CartItem(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default = 1)
    item_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return "Cart item for product {0}".format(self.product.title)

class Cart(models.Model):

    items = models.ManyToManyField(CartItem, blank=True)
    cart_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return str(self.id)
    def add_to_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
        if new_item not in cart.items.all():
            cart.items.add(new_item)
            cart.save()
    def remove_from_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        for cart_item in cart.items.all():
            if cart_item.product == product:
                cart.items.remove(cart_item)
                cart.save()

    def change_qty(self, qty, item_id):
        cart = self
        cart_item = CartItem.objects.get(id=int(item_id))
        cart_item.qty = int(qty)
        cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
        cart_item.save()
        new_cart_total = 0.00
        for item in cart.items.all():
            new_cart_total += float(item.item_total)
        cart.cart_total = new_cart_total
        cart.save()

ORDER_STATUS_CHOICES = {
    ('Принят в обработку', 'Принят в обработку'),
    ('Выполняется','Выполняется'),
    ('Оплачен','Оплачен')
}

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ForeignKey(Cart, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255, blank=True)
    buying_type = models.CharField(max_length=40, choices=(('Самовывоз','Самовывоз'),('Доставка','Доставка',)), default='Самовывоз')
    date = models.DateTimeField(auto_now_add=True)
    comments = models.TextField()
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES, default='Принят в обработку')


    def __str__(self):
        return "Заказ №{0}".format(str(self.id))

autoshop/shop/views.py
from __future__ import unicode_literals
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import login, authenticate
from .forms import OrderForm, RegistrationForm, LoginForm
from .models import Category, Product, CartItem, Cart, Order
from decimal import Decimal
from django.views.generic import View
from django.contrib.auth.models import User
# Create your views here.
def base_view(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        'categories': categories,
        'products': products,
        'cart': cart
    }
    return render(request, 'base.html', context)


def product_view(request, product_slug):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product = Product.objects.get(slug=product_slug)
    categories = Category.objects.all()
    context = {
        'cart': cart,
        'categories': categories,
        'product':product
    }
    return render(request, 'product.html', context)

def category_view(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    products_of_category = Product.objects.filter(category=category)
    categories = Category.objects.all()
    context = {
        'categories': categories,
        'category':category,
        'products_of_category':products_of_category
    }
    return render(request, 'category.html', context)

def cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart =Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        'cart':cart,
    }
    return render(request, 'cart.html', context)

def add_to_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.add_to_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total':cart.items.count(), 'cart_total_price':cart.cart_total})

def remove_from_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.remove_from_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total':cart.items.count(), 'cart_total_price':cart.cart_total})

def change_item_qty(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    qty = request.GET.get('qty')
    item_id = request.GET.get('item_id')
    cart.change_qty(qty, item_id)
    cart_item = CartItem.objects.get(id=int(item_id))
    return JsonResponse({'cart_total':cart.items.count(), 'item_total':cart_item.item_total, 'cart_total_price':cart.cart_total})

def checkout_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        'cart': cart,
    }
    return render(request, 'checkout.html', context)

def order_create_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    context = {
        'form': form,
        'cart': cart
    }
    return render(request, 'order.html', context)
def make_order_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    categories = Category.objects.all()
    if form.is_valid():
        name = form.cleaned_data['name']
        last_name = form.cleaned_data['last_name']
        phone = form.cleaned_data['phone']
        buying_type = form.cleaned_data['buying_type']
        address = form.cleaned_data['address']
        comments = form.cleaned_data['comments']
        new_order = Order.objects.create(
            user=request.user,
            items=cart,
            total=cart.cart_total,
            first_name=name,
            last_name=last_name,
            phone=phone,
            address=address,
            buying_type=buying_type,
            comments=comments
        )
        del request.session['cart_id']
        del request.session['total']
        return HttpResponseRedirect(reverse('thank_you'))
    return render(request, 'order.html', {'categories': categories})

def account_view(request):
    order = Order.objects.filter(user=request.user).order_by('-id')
    categories = Category.objects.all()
    context = {
        'order':order,
        'categories':categories
    }
    return render(request, 'account.html', context)

def registration_view(request):
    form = RegistrationForm(request.POST or None)
    categories = Category.objects.all()
    if form.is_valid():
        new_user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        email = form.cleaned_data['email']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        new_user.username = username
        new_user.set_password(password)
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.email = email
        new_user.save()
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    context = {
        'form': form,
        'categories': categories
    }
    return render(request, 'registration.html', context)


def login_view(request):
    form = LoginForm(request.POST or None)
    categories = Category.objects.all()
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    context = {
        'form': form,
        'categories': categories
    }
    return render(request, 'login.html', context)


# def search_form(request):
#     return render_to_response('search_form.html')

def search(request):
    error = False
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            error = True
        else:
            products = Product.objects.filter(title__icontains=q)
            return render(request, 'search_results.html',
                {'products': products, 'query': q})
    else:
        return render(request, 'search_form.html', {'error': error})

autoshop/shop/templates/account.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<h3 class="text-center">Личный кабинет пользователя {{ request.user }}</h3>
<hr>
<h4 class='text-center'>Ваши заказы</h4>
<table class='table'>
<tr style='background:lightblue;'>
	<td class='text-center'>Номер заказа</td>
	<td class='text-center'>Дата заказа</td>
	<td class='text-center'>Статус заказа</td>
	<td class='text-center'>Стоимость заказа</td>
	<td class='text-center'>Детали заказа</td>
	<td></td>
</tr>
{% for item in order %}
<tr>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.id }}</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.date }}</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.status }}</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.total }} руб.</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'><button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal-{{ item.id }}">
  Детали заказа
</button></td>
</tr>
{% endfor %}
</table>
<!-- Button trigger modal -->

<!-- Modal -->
{% for item in order %}
<div class="modal fade" id="myModal-{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Заказ № {{ item.id }}</h4>
      </div>
      <div class="modal-body">
      <h3>Товар</h3>
        <table class='table'>
        	{% for order_item in item.items.items.all %}
	        	<tr>
	       			<td>{{ order_item.product.title }}</td>
	       			<td>{{ order_item.qty }} шт.</td>
	       			<td>{{ order_item.item_total }} руб.</td>
	        	</tr>
        	{% endfor %}
        		 <tr>
	        		<td></td>
	        		<td>Итого</td>
	        		<td><strong>{{ item.items.cart_total }} руб.</strong></td>
	        	</tr>
        </table>
   		<h3>Заказчик</h3>
   		 <p>Имя: {{ item.first_name }}</p>
   		 <p>Фамилия: {{ item.last_name }}</p>
   		 <p>Телефон: {{ item.phone }}</p>
   		 <h3>Тип доставки</h3>
   		 <p>{% if item.buying_type == 'self' %} Самовывоз {% else %}Доставка{% endif %}</p>
   		 <p>{% if item.buying_type == 'delivery' %} {{ item.address }}{% endif %}</p>
   		 <h3>Комментарии к заказу</h3>
   		 <p>{{ item.comments }}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>
{% endfor %}
<script src='{% static "js/jquery.js" %}'></script>
<script>
    $(document).ready(function(){
        $('.add_to_cart').on('click', function(e){
            e.preventDefault()
            product_slug = $(this).attr('data-slug')
            data = {
                product_slug: product_slug
            }
            $.ajax({
                type: "GET",
                url: '{% url "add_to_cart" %}',
                data: data,
                success: function(data){
                    $("#cart_count").html(data.cart_total)

                }
            })
        })
    })
</script>
{% endblock content %}

autoshop/shop/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Интернет-магазин Электроника</title>

    <!-- Bootstrap Core CSS -->
   <link rel="stylesheet" href='{% static "css/bootstrap.css" %}'>

    <!-- Custom CSS -->
    <link rel="stylesheet" href='{% static "css/shop-homepage.css" %}'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Электроника</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    {% if not request.get_full_path == '/' %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Категории<span class="caret"></span></a>
                        <ul class="dropdown-menu">

                            {% for category in categories %}
                            <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    {% endif %}
                    {% if not request.user.is_authenticated %}
                    <li>
                        <p class="navbar-text">Здравствуйте, гость!</p>
                    </li>
                    <li>
						<a href='{% url "login" %}'>Войти</a>
					</li>
					<li>
						<a href='{% url "registration" %}'>Регистрация</a>
					</li>
                    {% else %}
                    <li>
                        <p class="navbar-text">Здравствуйте, {{ request.user }}</p>
                    </li>
                    <li>
                        <a href="{% url 'account' %}">Личный кабинет</a>
                    </li>
                    <li>
						<a href='{% url "logout" %}'>Выйти</a>
					</li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
						<a href='{% url "search" %}'>Поиск</a>
					</li>
                    <li><a href='{% url "cart" %}'> Корзина <span class="badge" id="cart_count">{% if not request.session.total%} 0 {% else %} {{ request.session.total }} {% endif %}</span></a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        {% block content %}
        <div class="row">

            <div class="col-md-3">
                <p class="lead">Категории</p>
                <div class="list-group">
                    {% for category in categories %}
                    <a href="{{ category.get_absolute_url }}" class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                </div>
            </div>

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                {% for product in products %}
                                {% if forloop.first %}
                                <div class="item active" >
                                    <a href='{{ product.get_absolute_url }}'>
                                    <img class="slide-image" src="{{ product.image.url }}" alt="" style="padding-left: 260px; width:80%; height:auto;">
                                    </a><br>
                                    <p class="text-center"><a href="{{ product.get_absolute_url }}"><button class="btn btn-primary">{{ product.title }}</button></a></p>
                                </div>
                                {% else %}
                                <div class="item">
                                    <a href='{{ product.get_absolute_url }}'>
                                    <img class="slide-image" src="{{ product.image.url }}" alt="" style="padding-left: 260px; width:80%; height:auto;">
                                    </a><br>
                                    <p class="text-center"><a href="{{ product.get_absolute_url }}"><button class="btn btn-primary">{{ product.title }}</button></a></p>
                                </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev" style="background:transparent;">
                                <span class="glyphicon glyphicon-chevron-left" style="color:black;"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next" style="background:transparent;">
                                <span class="glyphicon glyphicon-chevron-right" style="color:black;"></span>
                            </a>
                        </div>
                    </div>

                </div>

                <div class="row">
                    {% for product in products %}
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail" style='height: 450px; position: relative;'>
                            <a href='{{ product.get_absolute_url }}'>
                                <img src="{{ product.image.url }}" alt="" style='width:auto, max-height:100px'>
                            </a>
                            <div class="caption">

                                <h4 class="pull-right">{{ product.price }} руб.</h4>
                                <br>
                                <br>
                                <h4 class="pull-left"><p style="white-space: normal"><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></p></h4>
                                <div style='position: absolute; bottom: 10px; right:40px; left:5px;'>
								{% if request.user.is_authenticated %}<p class='text-right'><a href='#' class='add_to_cart' data-slug='{{ product.slug }}'><button class='btn btn-danger'>Добавить в корзину</button></a></p>{% else %} <small class="text-center">Заказывать товар могут только авторизованные пользователи. Пожалуйста, <a href="{% url 'login' %}">войдите</a> или <a href="{% url 'registration' %}">зарегистрируйтесь</a></small>{% endif %}
								</div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>

        </div>
        {% endblock content %}
    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p class="text-center">Copyright &copy; Electronic Shop 2019</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src='{% static "js/jquery.js" %}'></script>

    <!-- Bootstrap Core JavaScript -->
    <script src='{% static "js/bootstrap.js" %}'></script>
<script>
$(document).ready(function(){
	$('.add_to_cart').on('click', function(e){
		e.preventDefault()
		product_slug = $(this).attr('data-slug')
		data = {
			product_slug: product_slug
		}
		$.ajax({
			type: "GET",
			url: '{% url "add_to_cart" %}',
			data: data,
			success: function(data){
				$("#cart_count").html(data.cart_total)
			}
		})
	})
})
</script>

</body>

</html>

autoshop/shop/templates/checkout.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center">Ваш предварительный заказ</h3>
<br>
<table class="table">
    <tr>
        <td class="text-center"><strong>Товар</strong></td>
        <td class="text-center"><strong>Кол-во</strong></td>
        <td class="text-center"><strong>Цена</strong></td>
        <td class="text-center"></td>
    </tr>
    {% for item in cart.items.all %}
    <tr>
        <td class="text-center">{{ item.product.title }}</td>
        <td class="text-center">{{ item.qty }}</td>
        <td class="text-center">{{ item.item_total }} руб.</td>
        <td class="text-center"></td>
    </tr>
    {% endfor %}
    <tr>
        <td></td>
        <td class="text-center"><strong>Итого: </strong></td>
        <td class="text-center"><strong>{{ cart.cart_total }} руб.</strong></td>
        <td class="text-center"></td>
    </tr>
</table>
<a href="{% url 'create_order' %}" class="pull-right"><button class="btn btn-success">Оформить заказ</button> </a>
{% endblock content %}

autoshop/shop/templates/order.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class='text-center'>Оформление заказа</h3>
<hr>
<form action='{% url "make_order" %}' method="POST">
{% csrf_token %}
<div class="col-sm-4">
    {{ form.name|as_crispy_field }}
</div>
<div class="col-sm-4">
    {{ form.last_name|as_crispy_field }}
</div>
<div class="col-sm-4">
    {{ form.phone|as_crispy_field }}
</div>
    {{ form.buying_type|as_crispy_field }}
    {{ form.address|as_crispy_field }}
    {{ form.date|as_crispy_field }}
    {{ form.comments|as_crispy_field }}
    <input type="submit" class="btn btn-success" value="Оформить заказ">
</form>
<script src='{% static "js/jquery.js" %}'></script>
<script>
    $(document).ready(function(){
        $('#div_id_address').css('display','none')
        $('#id_buying_type').on('click', function(){
            buying_type = $(this).val()
            if(buying_type == 'delivery'){
                $('#div_id_address').css('display','block')
            }else{
                $('#div_id_address').css('display','none')
            }
        })
        $('#id_date_month').css('width', '100px', 'display', 'inline')
        $('#id_date_year').css('width', '100px', 'display', 'inline')
        $('#id_date_day').css('width', '100px', 'display', 'inline')
        $('#id_date_month').css('display', 'inline')
        $('#id_date_year').css('display', 'inline')
        $('#id_date_day').css('display', 'inline')
    })
</script>
{% endblock content %}